# Generated by Django 5.1.2 on 2025-04-22 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_message_receiver_message_sender_userfcmtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_chatrooms', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiator_chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
