# Generated by Django 5.1.2 on 2025-04-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='roomname',
        ),
    ]
