# Generated by Django 5.1.2 on 2025-04-27 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_name_chatroom_roomname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_message', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_previews', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_previews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
