# Generated by Django 5.1.2 on 2025-05-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_chatpreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='userfcmtoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
