# Generated by Django 5.1.2 on 2025-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userfcmtoken_token_alter_userfcmtoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='token',
            field=models.TextField(),
        ),
    ]
