# Generated by Django 5.1.2 on 2025-05-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_icon'),
        ('user', '0008_alter_userfcmtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='product.category'),
        ),
    ]
