# Generated by Django 5.1.2 on 2025-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpreview',
            name='unread',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
