# Generated by Django 5.1.2 on 2025-05-21 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatpreview',
            name='actual_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_receiver_previews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatpreview',
            name='actual_sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_sender_previews', to=settings.AUTH_USER_MODEL),
        ),
    ]
