# Generated by Django 5.1.2 on 2025-05-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_chatpreview_actual_receiver_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatpreview',
            options={'ordering': ['-time']},
        ),
    ]
