# Generated by Django 5.1.2 on 2025-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_points',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
