# Generated by Django 5.1.2 on 2025-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('new', models.BooleanField(default=False)),
                ('extra_field', models.JSONField(default=dict)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('sold', models.BooleanField(default=False)),
                ('datesold', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
