# Generated by Django 5.1.2 on 2025-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_categories_product_owner_product_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_field',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
