# Generated by Django 5.1.2 on 2025-05-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new',
            new_name='used',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
