# Generated by Django 5.1.2 on 2025-05-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_imagefile_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
