# Generated by Django 5.1.2 on 2025-05-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_negotiable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='negotiable',
        ),
    ]
