# Generated by Django 5.1.2 on 2025-05-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
