# Generated by Django 5.1.2 on 2025-05-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
