# Generated by Django 5.1.2 on 2025-05-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sticky',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sticky_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
