# Generated by Django 5.1.2 on 2025-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_is_sticky_product_sticky_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
