# Generated by Django 5.1.2 on 2025-06-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_in_cart_product_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='in_cart',
        ),
    ]
