# Generated by Django 5.1.2 on 2025-04-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/')),
                ('level', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('course', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_whatsapp_contact', models.CharField(max_length=25)),
                ('buyer_call_contact', models.CharField(blank=True, max_length=25, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
